version: '2.2'
services:
  nginx:
    build:
      context: .
      dockerfile: deployment/docker/Dockerfile.nginx
      args:
        PHP_FPM_SERVER: php
        PHP_FPM_PORT: 9000
    ports:
      - ${DOCKER_NGINX_EXTERNAL_PORT-80}:80
    depends_on:
      - php
    links:
      - php
    volumes:
      - .:/var/www/

  php:
    build:
      context: .
      dockerfile: deployment/docker/Dockerfile
      args:
        XDEBUG: "true"
    volumes:
      - .:/var/www/
      - ./deployment/docker/php.ini:/usr/local/etc/php/conf.d/php.ini
    environment:
      APP_ENV: local
    links:
      - mysql

volumes:
  mysqldata:
    driver: local
